import { EditorConfigProperties } from '../editorconfig';
import { SUPPORTED_DIAGNOSTICS, effectiveEditorConfigValue, isDiagnosticEnforced } from '../editorConfigRegistry';
import { DeclaredSymbol, SourceModel, TypeInfo, spans, typeAt } from '../naming/sourceModel';
import { Node, TextEdit } from '../parser';
import { lex } from '../syntax/lexer';
import type { RuleContext } from './editorConfigCodeStyle';
import { isRecoveredNode, lineEndAt, lineNumberAt, lineStartAt, modifiersOf } from './editorConfigSupport';

/**
 * Shared infrastructure of the code-quality (CA) and IDE diagnostics without a code-style option
 * (see `editorConfigQualityRules.ts`): gating on the diagnostic's severity, generated code and
 * suppressions, option reading, framework checks and the syntactic type lookup the rules use to
 * prove what a receiver is.
 */

/** True when `diagnosticId` is enforced for the file and the file is not generated code. */
export function isRuleActive(context: RuleContext, diagnosticId: string, source: string): boolean {
  return isDiagnosticEnforced(context.props, diagnosticId) && !isGeneratedCode(context.props, source, context.fileName);
}

/**
 * Generated code, which the .NET analyzers do not report on: `generated_code = true`, a generated
 * file name, or a leading `<auto-generated>` comment.
 */
export function isGeneratedCode(props: EditorConfigProperties, source: string, fileName: string | undefined): boolean {
  const generated = props.get('generated_code')?.trim().toLowerCase();
  if (generated === 'true') {
    return true;
  }

  if (generated !== 'false' && fileName && /(?:\.designer|\.generated|\.g|\.g\.i)\.cs$|^TemporaryGeneratedFile_/i.test(fileName)) {
    return true;
  }

  const header = /^\uFEFF?(?:\s*(?:\/\/[^\n]*|\/\*[\s\S]*?\*\/))*/.exec(source)?.[0] ?? '';

  return /<auto-?generated/i.test(header);
}

/** The reporter message of a rule: `CA1822 line 12: ...`. */
export function describeDiagnostic(diagnosticId: string, source: string, index: number, message: string): string {
  return `${diagnosticId} line ${lineNumberAt(source, index)}: ${message}`;
}

/**
 * A `dotnet_code_quality` option of a rule, with the .NET precedence: the rule's own setting, then
 * its category's, then the one for all rules.
 */
export function readCodeQualityOption(props: EditorConfigProperties, diagnosticId: string, option: string): string | undefined {
  const category = SUPPORTED_DIAGNOSTICS[diagnosticId]?.category;
  const value =
    props.get(`dotnet_code_quality.${diagnosticId}.${option}`) ??
    (category ? props.get(`dotnet_code_quality.${category}.${option}`) : undefined) ??
    props.get(`dotnet_code_quality.${option}`);

  return value?.trim().toLowerCase();
}

// ---------------------------------------------------------------------------------------------
// Suppressions
// ---------------------------------------------------------------------------------------------

interface PragmaDirective {
  readonly offset: number;
  readonly disable: boolean;
  /** Upper-cased diagnostic ids; empty for every warning. */
  readonly ids: readonly string[];
}

/** `#pragma warning disable/restore` directives and `[SuppressMessage]` attributes of a file. */
export class Suppressions {
  private readonly pragmas: PragmaDirective[] = [];

  constructor(source: string) {
    for (const trivia of lex(source).trivia) {
      if (trivia.type !== 'preproc_pragma') {
        continue;
      }

      const match = /^#\s*pragma\s+warning\s+(disable|restore)\b([^\r\n]*)/.exec(source.slice(trivia.start, trivia.end));
      if (match) {
        const ids = match[2]
          .replace(/\/\/.*$/, '')
          .split(',')
          .map((id) => id.trim().toUpperCase())
          .filter(Boolean);
        this.pragmas.push({ offset: trivia.start, disable: match[1] === 'disable', ids });
      }
    }
  }

  /** True when `diagnosticId` is suppressed at `node` (by a pragma, or an attribute on it or a containing declaration). */
  isSuppressed(diagnosticId: string, node: Node): boolean {
    return this.isSuppressedAt(diagnosticId, node.startIndex) || hasSuppressMessageAttribute(node, diagnosticId);
  }

  isSuppressedAt(diagnosticId: string, offset: number): boolean {
    const id = diagnosticId.toUpperCase();
    let disabled = false;
    for (const pragma of this.pragmas) {
      if (pragma.offset >= offset) {
        break;
      }

      if (pragma.ids.length === 0 || pragma.ids.includes(id)) {
        disabled = pragma.disable;
      }
    }

    return disabled;
  }
}

function hasSuppressMessageAttribute(node: Node, diagnosticId: string): boolean {
  const pattern = new RegExp(`"${diagnosticId}\\b`, 'i');
  for (let current: Node | null = node; current; current = current.parent) {
    for (const attribute of attributesOf(current)) {
      if (/^(?:[\w.]+\.)?SuppressMessage(?:Attribute)?$/.test(attributeName(attribute)) && pattern.test(attribute.text)) {
        return true;
      }
    }
  }

  return false;
}

/** The attributes applied to a declaration (not to its return value or parameters). */
export function attributesOf(declaration: Node): Node[] {
  return declaration.namedChildren
    .filter((child) => child.type === 'attribute_list' && !/^\[\s*(?:return|param|assembly|module)\s*:/.test(child.text))
    .flatMap((list) => list.namedChildren.filter((child) => child.type === 'attribute'));
}

/** An attribute's name as written, without the `Attribute` suffix and type arguments. */
export function attributeName(attribute: Node): string {
  const name = (attribute.childForFieldName('name') ?? attribute.namedChild(0))?.text ?? attribute.text;

  return name.replace(/\s+/g, '').replace(/<.*$/, '').replace(/Attribute$/, '');
}

/** The simple name of an attribute: `System.ObsoleteAttribute` -> `Obsolete`. */
export function attributeSimpleName(attribute: Node): string {
  return attributeName(attribute).split('.').pop() ?? '';
}

/** True when the declaration or one of its containing types carries `[Obsolete]`. */
export function isOnObsoleteChain(declaration: Node): boolean {
  for (let current: Node | null = declaration; current; current = current.parent) {
    if (attributesOf(current).some((attribute) => attributeSimpleName(attribute) === 'Obsolete')) {
      return true;
    }
  }

  return false;
}

// ---------------------------------------------------------------------------------------------
// Declarations, accessibility and modifiers
// ---------------------------------------------------------------------------------------------

export const TYPE_DECLARATIONS = ['class_declaration', 'struct_declaration', 'record_declaration', 'interface_declaration', 'enum_declaration'];

/**
 * True when the parser could not make sense of a member declaration of the type (a tuple type as
 * a generic argument, for instance): its member list is then incomplete, so nothing may rely on it.
 */
export function hasBrokenMemberDeclarations(type: Node): boolean {
  return (type.childForFieldName('body')?.namedChildren ?? []).some(isRecoveredNode);
}

export function isRecordStruct(declaration: Node): boolean {
  return declaration.type === 'record_declaration' && declaration.children.some((child) => child.type === 'struct');
}

/** Visibility of a declaration from outside: Roslyn's resultant `SymbolVisibility`. */
export type Visibility = 'public' | 'internal' | 'private';

/**
 * The resultant visibility of a type or member: the most restrictive of its own accessibility and
 * that of each containing type. `protected` counts as public (derived types in other assemblies).
 */
export function resultantVisibility(declaration: Node): Visibility {
  let visibility: Visibility = 'public';
  for (let current: Node | null = declaration; current; current = current.parent) {
    if (ACCESSIBILITY_DECLARATIONS[current.type] !== true) {
      continue;
    }

    const own = declaredVisibility(current);
    if (own === 'private' || (own === 'internal' && visibility === 'public')) {
      visibility = own;
    }
  }

  return visibility;
}

const ACCESSIBILITY_DECLARATIONS: Record<string, true> = {
  class_declaration: true,
  struct_declaration: true,
  record_declaration: true,
  interface_declaration: true,
  enum_declaration: true,
  delegate_declaration: true,
  method_declaration: true,
  property_declaration: true,
  indexer_declaration: true,
  event_declaration: true,
  event_field_declaration: true,
  field_declaration: true,
  constructor_declaration: true,
  operator_declaration: true,
  conversion_operator_declaration: true,
};

/** The accessibility a declaration has on its own (Roslyn's `DeclaredAccessibility`), as a visibility group. */
export function declaredVisibility(declaration: Node): Visibility {
  const modifiers = new Set(modifiersOf(declaration).map((modifier) => modifier.text));
  if (modifiers.has('file')) {
    return 'private';
  }

  if (modifiers.has('public') || (modifiers.has('protected') && !modifiers.has('private'))) {
    return 'public';
  }

  if (modifiers.has('internal') || (modifiers.has('protected') && modifiers.has('private'))) {
    return 'internal';
  }

  if (modifiers.has('private')) {
    return 'private';
  }

  // No modifier: interface members are public, top-level types internal, everything else private.
  const container = containingTypeDeclaration(declaration);
  if (!container) {
    return 'internal';
  }

  return container.type === 'interface_declaration' ? 'public' : 'private';
}

/** The type declaration directly containing a member or nested type, if any. */
export function containingTypeDeclaration(node: Node): Node | undefined {
  const list = node.parent;
  if (list?.type !== 'declaration_list') {
    return undefined;
  }

  const owner = list.parent;

  return owner && TYPE_DECLARATIONS.includes(owner.type) ? owner : undefined;
}

/** The default modifier order of the .NET code style (`csharp_preferred_modifier_order`). */
const DEFAULT_MODIFIER_ORDER = [
  'public', 'private', 'protected', 'internal', 'file', 'static', 'extern', 'new', 'virtual', 'abstract',
  'sealed', 'override', 'readonly', 'unsafe', 'required', 'volatile', 'async',
];

/**
 * An edit adding `modifier` to a declaration at its place in `csharp_preferred_modifier_order`
 * (else the .NET default order); `partial` stays last. `before` is where a declaration without
 * modifiers gets it: the first token after its attributes.
 */
export function addModifierEdit(props: EditorConfigProperties, declaration: Node, modifier: string, before: Node): TextEdit {
  const preferred = effectiveEditorConfigValue(props, 'csharp_preferred_modifier_order')
    ?.split(',')
    .map((name) => name.trim());
  const order = preferred?.includes(modifier) ? preferred : DEFAULT_MODIFIER_ORDER;
  const rank = order.indexOf(modifier);
  const modifiers = modifiersOf(declaration);
  const after = modifiers.find((existing) => existing.text === 'partial' || order.indexOf(existing.text) > rank);
  if (after) {
    return { start: after.startIndex, end: after.startIndex, text: `${modifier} ` };
  }

  const last = modifiers[modifiers.length - 1];

  return last
    ? { start: last.endIndex, end: last.endIndex, text: ` ${modifier}` }
    : { start: before.startIndex, end: before.startIndex, text: `${modifier} ` };
}

// ---------------------------------------------------------------------------------------------
// Removing declarations
// ---------------------------------------------------------------------------------------------

/**
 * The edit deleting a whole declaration with the doc comments directly above it, as full lines,
 * plus one blank line when the removal would otherwise leave two in a row or a blank line next to
 * a brace. `undefined` when the declaration shares a line with other code or contains
 * preprocessor directives.
 */
export function removeDeclarationEdit(source: string, declaration: Node): TextEdit | undefined {
  let first: Node = declaration;
  for (let previous = declaration.previousNamedSibling; previous?.type === 'comment'; previous = previous.previousNamedSibling) {
    const between = source.slice(previous.endIndex, first.startIndex);
    if (!/^[ \t]*\r?\n[ \t]*$/.test(between) || !previous.text.startsWith('///')) {
      break;
    }

    first = previous;
  }

  const start = lineStartAt(source, first.startIndex);
  const lineEnd = lineEndAt(source, declaration.endIndex);
  if (source.slice(start, first.startIndex).trim() || source.slice(declaration.endIndex, lineEnd).trim()) {
    return undefined;
  }

  const text = source.slice(first.startIndex, declaration.endIndex);
  if (/^[ \t]*#/m.test(text)) {
    return undefined;
  }

  let end = source[lineEnd] === '\r' ? lineEnd + 2 : lineEnd + 1;
  end = Math.min(end, source.length);

  const previousLine = start > 0 ? source.slice(lineStartAt(source, start - 1), start).trim() : '';
  const nextLineEnd = lineEndAt(source, end);
  const nextLine = source.slice(end, nextLineEnd).trim();
  const nextBreakEnd = Math.min(source[nextLineEnd] === '\r' ? nextLineEnd + 2 : nextLineEnd + 1, source.length);
  if (nextLine === '' && end < source.length && (previousLine === '' || previousLine.endsWith('{'))) {
    end = nextBreakEnd;
  } else if (previousLine === '' && start > 0 && nextLine.startsWith('}')) {
    return { start: lineStartAt(source, start - 1), end, text: '' };
  }

  return { start, end, text: '' };
}

// ---------------------------------------------------------------------------------------------
// Target frameworks
// ---------------------------------------------------------------------------------------------

/** APIs a fix may introduce that older target frameworks lack. */
export type FrameworkApi =
  /** `Array.Empty<T>()`: .NET Framework 4.6, .NET Standard 2.0, .NET Core. */
  | 'arrayEmpty'
  /** `string` char overloads and `Contains(string, StringComparison)`: .NET Core 2.1, .NET Standard 2.1. */
  | 'stringCharOverloads'
  /** `Dictionary<TKey, TValue>.TryAdd` and `Enum.Parse<TEnum>`: .NET Core 2.0, .NET Standard 2.1. */
  | 'coreApis'
  /** `Marshal.SizeOf<T>()`: .NET Framework 4.5.1, .NET Standard 2.0, .NET Core. */
  | 'marshalSizeOfGeneric'
  /** `HttpClient.GetStringAsync(string, CancellationToken)` and friends: .NET 5. */
  | 'net5'
  /** `TextReader.ReadLineAsync(CancellationToken)`/`ReadToEndAsync(CancellationToken)`: .NET 7. */
  | 'net7';

/**
 * The first version of each framework family with the API (`[.NET Core, .NET Standard, .NET
 * Framework, .NET 5+]`, versions as `major * 100 + minor * 10 + patch`); `undefined`: never.
 */
const API_VERSIONS: Record<FrameworkApi, readonly [number | undefined, number | undefined, number | undefined, number]> = {
  arrayEmpty: [100, 200, 460, 500],
  stringCharOverloads: [210, 210, undefined, 500],
  coreApis: [200, 210, undefined, 500],
  marshalSizeOfGeneric: [100, 200, 451, 500],
  net5: [undefined, undefined, undefined, 500],
  net7: [undefined, undefined, undefined, 700],
};

/** True/false when every target framework has/lacks the API; `undefined` when a framework is unknown. */
export function frameworksSupport(frameworks: readonly string[] | undefined, api: FrameworkApi): boolean | undefined {
  if (!frameworks || frameworks.length === 0) {
    return undefined;
  }

  let supported = true;
  for (const framework of frameworks) {
    const result = frameworkSupports(framework.trim().toLowerCase(), api);
    if (result === undefined) {
      return undefined;
    }

    supported &&= result;
  }

  return supported;
}

function frameworkSupports(framework: string, api: FrameworkApi): boolean | undefined {
  const [core, standard, netFramework, modern] = API_VERSIONS[api];
  const atLeast = (version: number, first: number | undefined): boolean => first !== undefined && version >= first;
  const modernMatch = /^net(\d+)\.(\d+)/.exec(framework);
  if (modernMatch) {
    const major = Number(modernMatch[1]);

    return major >= 5 ? atLeast(major * 100, modern) : undefined;
  }

  const coreMatch = /^netcoreapp(\d+)\.(\d+)/.exec(framework);
  if (coreMatch) {
    return atLeast(Number(coreMatch[1]) * 100 + Number(coreMatch[2]) * 10, core);
  }

  const standardMatch = /^netstandard(\d+)\.(\d+)/.exec(framework);
  if (standardMatch) {
    return atLeast(Number(standardMatch[1]) * 100 + Number(standardMatch[2]) * 10, standard);
  }

  const frameworkMatch = /^net(\d)(\d)(\d?)$/.exec(framework);
  if (frameworkMatch) {
    return atLeast(Number(frameworkMatch[1]) * 100 + Number(frameworkMatch[2]) * 10 + Number(frameworkMatch[3] || 0), netFramework);
  }

  return undefined;
}

// ---------------------------------------------------------------------------------------------
// Declared types
// ---------------------------------------------------------------------------------------------

/** Removes whitespace, `global::` and a trailing nullable `?` from a type as written. */
export function normalizeType(text: string): string {
  return text.replace(/\s+/g, '').replace(/global::/g, '').replace(/\?$/, '');
}

/** `System.Collections.Generic.List<int>` -> `List`; `int[]` -> `int[]`. */
export function simpleTypeName(type: string): string {
  if (type.endsWith(']')) {
    return type;
  }

  const withoutArguments = type.replace(/<.*$/, '');

  return withoutArguments.slice(withoutArguments.lastIndexOf('.') + 1);
}

/** True when the type as written has type arguments: `List<int>`. */
export function isGenericType(type: string): boolean {
  return /^[^<]+<.+>$/.test(type);
}

/**
 * Looks up the declared type of simple expressions from the file's syntax: literals, object and
 * array creation, and names (locals, parameters, fields and properties of the enclosing type)
 * declared with an explicit type, or with `var` and one of those initializers. Anything whose
 * declaration or scope cannot be pinned down syntactically yields `undefined`.
 */
export class DeclaredTypes {
  private readonly declaredTypeNames: ReadonlySet<string>;

  constructor(
    private readonly model: SourceModel,
    projectTypeNames: ReadonlySet<string> = new Set()
  ) {
    this.declaredTypeNames = new Set([...model.types.map((type) => type.name), ...projectTypeNames]);
  }

  /** True when the file or project declares a type with this simple name (so a BCL name may not mean the BCL type). */
  declaresType(name: string): boolean {
    return this.declaredTypeNames.has(name);
  }

  typeOf(expression: Node, depth = 0): string | undefined {
    const node = unwrapParentheses(expression);
    switch (node.type) {
      case 'string_literal':
      case 'verbatim_string_literal':
      case 'raw_string_literal':
      case 'interpolated_string_expression':
        return 'string';
      case 'character_literal':
        return 'char';
      case 'object_creation_expression': {
        const type = node.childForFieldName('type');

        return type ? normalizeType(type.text) : undefined;
      }
      case 'array_creation_expression': {
        const type = node.namedChildren.find((child) => child.type === 'array_type');

        return type ? normalizeType(type.text).replace(/\[[^\]]*\]/g, (rank) => `[${rank.replace(/[^,]/g, '')}]`) : undefined;
      }
      case 'identifier':
        return depth > 2 ? undefined : this.typeOfName(node.text, node.startIndex, depth);
      case 'member_access_expression': {
        const receiver = node.childForFieldName('expression');
        const name = node.childForFieldName('name');
        if (receiver?.type !== 'this_expression' || name?.type !== 'identifier') {
          return undefined;
        }

        const type = typeAt(this.model, node.startIndex);
        const member = type ? this.fieldOrProperty(type, name.text) : undefined;

        return member ? this.symbolType(member, depth) : undefined;
      }
      default:
        return undefined;
    }
  }

  /** The declared type of a simple name at `offset`. */
  typeOfName(name: string, offset: number, depth = 0): string | undefined {
    const symbol = this.symbolAt(name, offset);

    return symbol ? this.symbolType(symbol, depth) : undefined;
  }

  /**
   * The type a simple name was declared with explicitly, as written without whitespace (keeping a
   * nullable `?`); `undefined` for `var` or an unknown declaration.
   */
  declaredTypeText(name: string, offset: number): string | undefined {
    const text = this.symbolAt(name, offset)?.declaredType?.replace(/\s+/g, '');

    return text && text !== 'var' ? text : undefined;
  }

  /** The local, parameter, field or property a simple name at `offset` refers to, when that is certain. */
  private symbolAt(name: string, offset: number): DeclaredSymbol | undefined {
    const local = this.localDeclaration(name, offset);
    if (local !== undefined) {
      return local ?? undefined;
    }

    for (let type = typeAt(this.model, offset); type; type = type.parent) {
      if (type.memberNames.has(name)) {
        return this.fieldOrProperty(type, name);
      }

      // An inherited member of the same name would hide an outer type's member.
      if (type.hasBaseList || type.isPartial) {
        return undefined;
      }
    }

    return undefined;
  }

  /**
   * The innermost local, parameter or range variable named `name` in scope at `offset`;
   * `undefined` when there is none, `null` when one exists whose scope is not known precisely.
   */
  localDeclaration(name: string, offset: number): DeclaredSymbol | undefined | null {
    let best: DeclaredSymbol | undefined;
    for (const symbol of this.model.symbols) {
      // Primary constructor parameters are in scope in the whole type, like its members.
      const primaryParameter = symbol.category === 'parameter' && symbol.owner !== undefined && TYPE_DECLARATIONS.includes(symbol.owner.type);
      if (
        symbol.name !== name ||
        primaryParameter ||
        (symbol.category !== 'local' && symbol.category !== 'parameter' && symbol.category !== 'range') ||
        !symbol.region ||
        !spans(symbol.region, offset, offset)
      ) {
        continue;
      }

      if (!symbol.regionPrecise) {
        return null;
      }

      if (!best || (best.region && symbol.region.startIndex >= best.region.startIndex)) {
        best = symbol;
      }
    }

    return best;
  }

  private fieldOrProperty(type: TypeInfo, name: string): DeclaredSymbol | undefined {
    if (type.isPartial) {
      return undefined;
    }

    const members = this.model.symbols.filter((symbol) => symbol.category === 'member' && symbol.type === type && symbol.name === name);

    return members.length === 1 && (members[0].kind === 'field' || members[0].kind === 'property') ? members[0] : undefined;
  }

  private symbolType(symbol: DeclaredSymbol, depth: number): string | undefined {
    const declared = symbol.declaredType ? normalizeType(symbol.declaredType) : undefined;
    if (declared !== 'var') {
      return declared || undefined;
    }

    // `var name = <initializer>;`
    const declarator = symbol.nameNode.parent;
    const initializer = declarator?.type === 'variable_declarator'
      ? declarator.namedChildren.find((child) => child.type === 'equals_value_clause')?.namedChildren[0]
      : undefined;

    return initializer ? this.typeOf(initializer, depth + 1) : undefined;
  }
}

export function unwrapParentheses(node: Node): Node {
  let current = node;
  while (current.type === 'parenthesized_expression' && current.namedChildren.length === 1) {
    current = current.namedChildren[0];
  }

  return current;
}

/** The expression `node` is part of once parentheses around it are skipped. */
export function parentSkippingParentheses(node: Node): { parent: Node | null; child: Node } {
  let child = node;
  let parent = node.parent;
  while (parent?.type === 'parenthesized_expression') {
    child = parent;
    parent = parent.parent;
  }

  return { parent, child };
}

/** True when `node` is inside a lambda or anonymous method (which may be an expression tree). */
export function isInsideLambda(node: Node, stop?: Node): boolean {
  for (let current = node.parent; current && current !== stop; current = current.parent) {
    if (current.type === 'lambda_expression' || current.type === 'anonymous_method_expression') {
      return true;
    }
  }

  return false;
}

/** True when `node` is inside an attribute (its arguments are persisted to metadata). */
export function isInsideAttribute(node: Node): boolean {
  for (let current = node.parent; current; current = current.parent) {
    if (current.type === 'attribute_list') {
      return true;
    }
  }

  return false;
}

/** The value of a C# string literal token with a single character, or `undefined`. */
export function singleCharacterOf(literal: Node): string | undefined {
  const text = literal.text;
  let body: string;
  if (literal.type === 'string_literal' && /^"[\s\S]*"$/.test(text) && !text.startsWith('"""')) {
    body = unescapeRegular(text.slice(1, -1)) ?? '';
  } else if (literal.type === 'verbatim_string_literal' && /^@"[\s\S]*"$/.test(text)) {
    body = text.slice(2, -1).replace(/""/g, '"');
  } else {
    return undefined;
  }

  return body.length === 1 ? body : undefined;
}

const SIMPLE_ESCAPES: Record<string, string> = {
  "'": "'", '"': '"', '\\': '\\', '0': '\0', a: '\x07', b: '\b', f: '\f', n: '\n', r: '\r', t: '\t', v: '\v', e: '\x1b',
};

function unescapeRegular(body: string): string | undefined {
  let result = '';
  for (let i = 0; i < body.length; i++) {
    const c = body[i];
    if (c !== '\\') {
      result += c;
      continue;
    }

    const next = body[i + 1];
    if (next === undefined) {
      return undefined;
    }

    if (SIMPLE_ESCAPES[next] !== undefined) {
      result += SIMPLE_ESCAPES[next];
      i++;
    } else if (next === 'u' && /^[0-9a-fA-F]{4}$/.test(body.slice(i + 2, i + 6))) {
      result += String.fromCharCode(parseInt(body.slice(i + 2, i + 6), 16));
      i += 5;
    } else if (next === 'U' && /^[0-9a-fA-F]{8}$/.test(body.slice(i + 2, i + 10))) {
      result += String.fromCodePoint(parseInt(body.slice(i + 2, i + 10), 16));
      i += 9;
    } else if (next === 'x') {
      const hex = /^[0-9a-fA-F]{1,4}/.exec(body.slice(i + 2))?.[0];
      if (!hex) {
        return undefined;
      }

      result += String.fromCharCode(parseInt(hex, 16));
      i += 1 + hex.length;
    } else {
      return undefined;
    }
  }

  return result;
}

/** A C# character literal for `c`. */
export function charLiteral(c: string): string {
  switch (c) {
    case "'":
      return "'\\''";
    case '\\':
      return "'\\\\'";
    case '\0':
      return "'\\0'";
    case '\n':
      return "'\\n'";
    case '\r':
      return "'\\r'";
    case '\t':
      return "'\\t'";
  }

  const code = c.charCodeAt(0);
  if (code < 0x20 || code === 0x7f || (code >= 0x80 && code <= 0x9f) || (code >= 0xd800 && code <= 0xdfff) || /\s/.test(c) && c !== ' ') {
    return `'\\u${code.toString(16).padStart(4, '0')}'`;
  }

  return `'${c}'`;
}
