// Writes the public top-level types (with the arities of generic ones) and extension method names of the .NET reference packs as a TypeScript module:
//   dotnet run --project scripts/bclIndex -- <output.ts> <refPackDir>...
// src/cleanup/usings/bclIndex.generated.ts is generated with the Microsoft.NETCore.App.Ref and Microsoft.AspNetCore.App.Ref packs, e.g.
//   dotnet run --project scripts/bclIndex -- src/cleanup/usings/bclIndex.generated.ts /usr/lib/dotnet/packs/Microsoft.NETCore.App.Ref/10.0.12 /usr/lib/dotnet/packs/Microsoft.AspNetCore.App.Ref/10.0.12
// Only the reference assemblies under ref/<tfm>/ are read: the analyzers/ folder of a pack holds analyzers and source
// generators, whose types no compilation can reference.
using System.Reflection.Metadata;
using System.Reflection.PortableExecutable;

var types = new SortedDictionary<string, SortedSet<string>>(StringComparer.Ordinal);
var arities = new SortedDictionary<string, SortedDictionary<string, SortedSet<int>>>(StringComparer.Ordinal);
var extensions = new SortedDictionary<string, SortedSet<string>>(StringComparer.Ordinal);

foreach (var directory in args.Skip(1))
{
    foreach (var file in Directory.EnumerateFiles(Path.Combine(directory, "ref"), "*.dll", SearchOption.AllDirectories))
    {
        using var stream = File.OpenRead(file);
        using var pe = new PEReader(stream);
        if (!pe.HasMetadata)
        {
            continue;
        }

        var reader = pe.GetMetadataReader();
        foreach (var handle in reader.TypeDefinitions)
        {
            var type = reader.GetTypeDefinition(handle);
            var visibility = type.Attributes & System.Reflection.TypeAttributes.VisibilityMask;
            if (visibility != System.Reflection.TypeAttributes.Public)
            {
                continue;
            }

            var ns = reader.GetString(type.Namespace);
            var metadataName = reader.GetString(type.Name);
            var name = StripArity(metadataName);
            if (name.StartsWith('<') || name == "<Module>")
            {
                continue;
            }

            Add(types, ns, name);
            if (!arities.TryGetValue(ns, out var byName))
            {
                arities[ns] = byName = new SortedDictionary<string, SortedSet<int>>(StringComparer.Ordinal);
            }

            if (!byName.TryGetValue(name, out var set))
            {
                byName[name] = set = new SortedSet<int>();
            }

            set.Add(Arity(metadataName));
            foreach (var methodHandle in type.GetMethods())
            {
                var method = reader.GetMethodDefinition(methodHandle);
                if ((method.Attributes & System.Reflection.MethodAttributes.MemberAccessMask) == System.Reflection.MethodAttributes.Public && IsExtension(reader, method))
                {
                    Add(extensions, ns, reader.GetString(method.Name));
                }
            }
        }
    }
}

// A name every declaration of which takes no type parameters is not listed in BCL_GENERIC_TYPES.
var generic = new SortedDictionary<string, SortedSet<string>>(StringComparer.Ordinal);
foreach (var (ns, byName) in arities)
{
    foreach (var (name, counts) in byName.Where(entry => entry.Value.Any(count => count > 0)))
    {
        foreach (var count in counts)
        {
            Add(generic, ns, $"{name}`{count}");
        }
    }
}

var output = new System.Text.StringBuilder();
output.Append("// Generated by scripts/bclIndex from the .NET reference packs; do not edit.\n");
output.Append("// Namespace -> space-separated public top-level type names (generic arity stripped) / extension method names.\n\n");
Write(output, "BCL_TYPES", types);
output.Append('\n');
output.Append("// Namespace -> the arities of the type names above that have a generic declaration, as Name`arity (Name`0: the non-generic one).\n");
Write(output, "BCL_GENERIC_TYPES", generic);
output.Append('\n');
Write(output, "BCL_EXTENSION_METHODS", extensions);
File.WriteAllText(args[0], output.ToString());

static void Write(System.Text.StringBuilder output, string name, SortedDictionary<string, SortedSet<string>> map)
{
    output.Append("export const ").Append(name).Append(": Readonly<Record<string, string>> = {\n");
    foreach (var (ns, names) in map)
    {
        output.Append("  '").Append(ns).Append("': '").Append(string.Join(' ', names)).Append("',\n");
    }

    output.Append("};\n");
}

static void Add(SortedDictionary<string, SortedSet<string>> map, string ns, string name)
{
    if (!map.TryGetValue(ns, out var set))
    {
        map[ns] = set = new SortedSet<string>(StringComparer.Ordinal);
    }

    set.Add(name);
}

static string StripArity(string name)
{
    var tick = name.IndexOf('`', StringComparison.Ordinal);

    return tick < 0 ? name : name[..tick];
}

static int Arity(string metadataName)
{
    var tick = metadataName.IndexOf('`', StringComparison.Ordinal);

    return tick < 0 ? 0 : int.Parse(metadataName[(tick + 1)..], System.Globalization.CultureInfo.InvariantCulture);
}

static bool IsExtension(MetadataReader reader, MethodDefinition method)
{
    foreach (var attributeHandle in method.GetCustomAttributes())
    {
        var attribute = reader.GetCustomAttribute(attributeHandle);
        if (attribute.Constructor.Kind == HandleKind.MemberReference)
        {
            var member = reader.GetMemberReference((MemberReferenceHandle)attribute.Constructor);
            if (member.Parent.Kind == HandleKind.TypeReference
                && reader.GetString(reader.GetTypeReference((TypeReferenceHandle)member.Parent).Name) == "ExtensionAttribute")
            {
                return true;
            }
        }
        else if (attribute.Constructor.Kind == HandleKind.MethodDefinition)
        {
            var ctor = reader.GetMethodDefinition((MethodDefinitionHandle)attribute.Constructor);
            if (reader.GetString(reader.GetTypeDefinition(ctor.GetDeclaringType()).Name) == "ExtensionAttribute")
            {
                return true;
            }
        }
    }

    return false;
}
